[package]
name = "rust-wasm-sample"
version = "0.1.0"
authors = ["konojunya <junya03dance@gmail.com>"]
repository = "https://github.com/konojunya/rust-wasm-sample"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
